# Generated by Django 5.2.3 on 2025-08-11 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('attendees', models.CharField(blank=True, max_length=500)),
                ('meeting_type', models.CharField(choices=[('interview', 'Interview'), ('networking', 'Networking'), ('followup', 'Follow-up'), ('assessment', 'Assessment'), ('other', 'Other')], default='interview', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
