# Generated by Django 5.2.3 on 2025-08-11 22:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
